### ISSUE TITLE
About the size of base graph

### ISSUE THREAD

**Issue by LLMforScience** [Wuyxin/DIR-GNN#13]
Thank you for your work. I want to ask why do you change the size of base graph, and why the sizes of base graphs are different in the training and testing?

**Comment by Wuyxin** [comment]
Hi,

Thanks for your interests. In Section 3.1 of our paper, we stated that "Besides, we include graphs with large bases to further magnify the distribution gaps". This is also following [https://arxiv.org/abs/1905.02850](https://arxiv.org/abs/1905.02850) since we are interested in whether the GNNs can generalize to larger graphs.

**Comment by LLMforScience** [comment]
Thank you for your reply which addresses my questions.
